---
- name: "STEP 1"
  shell: scripts/buildcluster_1.sh >> logs/log_1.txt
  ignore_errors: yes

- name: "STEP 2"
  shell: scripts/buildcluster_2.sh >> logs/log_2.txt
  ignore_errors: yes 

- name: "STEP 3"
  shell: scripts/buildcluster_3.sh >> logs/log_3.txt
  ignore_errors: yes 

# - name: "STEP 4 - Killing ssh tunnel to cluster"
#   shell: ps axuf | grep 2222 | grep ssh | awk '{ print "kill -9 " $1}' >> logs/log_5.txt

